import { uploadToStorage } from '@/lib/storage';

export async function processStyledImage(originalUrl: string, logoUrl: string, price: string, context: string) {
    if (process.env.PHOTOROOM_API_KEY) {
        try {
            // 1. Get original image data
            let imageBuffer: Buffer;
            if (originalUrl.startsWith('/uploads/')) {
                // Handle local uploads fallback
                const fs = await import('fs');
                const path = await import('path');
                imageBuffer = fs.readFileSync(path.join(process.cwd(), 'public', originalUrl));
            } else {
                // Handle remote storage URLs
                const res = await fetch(originalUrl);
                if (!res.ok) throw new Error("Failed to fetch original image");
                imageBuffer = Buffer.from(await res.arrayBuffer());
            }

            // 2. Prepare FormData for Photoroom API
            const formData = new FormData();
            formData.append('imageFile', new Blob([imageBuffer as any], { type: 'image/jpeg' }), 'product.jpg');

            const prompt = `Luxury jewelry display, high-end commercial photography, professional lighting, elegant composition. Theme: ${context}`;
            formData.append('background.prompt', prompt);

            // 3. Call Photoroom API
            const prRes = await fetch('https://image-api.photoroom.com/v2/edit', {
                method: 'POST',
                headers: {
                    'x-api-key': process.env.PHOTOROOM_API_KEY
                },
                body: formData
            });

            if (!prRes.ok) {
                const errText = await prRes.text();
                console.error("Photoroom error:", errText);
                throw new Error("Photoroom generation failed");
            }

            // 4. Read result and upload it back to our storage
            const resultBuffer = Buffer.from(await prRes.arrayBuffer());
            const fileName = `campaigns/styled/${Date.now()}-styled-product.jpg`;

            // Re-upload the newly styled image generated by Photoroom
            const styledUrl = await uploadToStorage(fileName, resultBuffer, 'image/jpeg');

            return styledUrl;
        } catch (e) {
            console.error("Image processing error:", e);
        }
    }

    // Graceful fallback if no API key or if API request fails
    return `${originalUrl}?styled=true&theme=luxury`;
}

export async function processCompositeImage(styledImageUrls: string[]) {
    // Graceful fallback: take the first styled image as a "composite" wrapper
    // Since Photoroom primarily focuses on background replacement for individual objects
    return styledImageUrls[0] || '';
}
